### ISSUE TITLE
get_event by id gives a resource id invalid error

### ISSUE THREAD

**Issue by AustinMCrane** [Ennovar/googlecal#3]
when i run the delete_event tests i want to be able to verify that the event exists with a simple get_event method but i get the following error from the get_event method
```
  1) Googlecal Googlecal::Base.delete_event should delete an event
     # get_event is not working for some reason
     Failure/Error: result = @calendar_service.get_acl(calendar_id, event_id)

     Google::Apis::ClientError:
       invalid: Invalid resource id value.
     # ./lib/googlecal.rb:75:in `get_event'
     # ./spec/googlecal_spec.rb:44:in `block (4 levels) in <top (required)>'
```

**Comment by AustinMCrane** [comment]
i fixed this, i was using the wrong function to get events
```
result = @calendar_service.get_event(calendar_id, event_id)
```
and not
```
result = @calendar_service.get_acl(calendar_id, event_id)
```
